basePath: /v1
consumes:
- application/json
- application/multipartform
host: https://ecommerce-go.herokuapp.com
info:
  contact:
    email: marcelo_alfahot@hotmail.com
    name: Marcelo Oliveira
  description: Documentation of our ecommerce API.
  title: Grab And Cash API.
  version: 1.0.0
paths:
  /login:
    post:
      description: Login na aplicação
      operationId: response
      responses:
        "200":
          description: Login
        "500":
          description: Error
      tags:
      - user
  /signUp:
    post:
      description: Adiciona novo usuário
      operationId: response
      responses:
        "201":
          description: User created
        "500":
          description: Error
      tags:
      - user
produces:
- application/json
schemes:
- https
security:
- bearer: []
securityDefinitions:
  bearer:
    type: apiKey
swagger: "2.0"
