basePath: /v1
consumes:
  - application/json
  - application/multipartform
host: https://ecommerce-go.herokuapp.com
info:
  contact:
    email: marcelo_alfahot@hotmail.com
    name: Marcelo Oliveira
  description: Documentation of our ecommerce API.
  title: Grab And Cash API.
  version: 1.0.0
paths:
  /login:
    post:
      tags:
        - user
      parameters:
        - name: email
          in: body
          description: User Email
          required: true
        - name: password
          in: body
          description: User Password
          required: true
      description: Login na aplicação
      operationId: response
      responses:
        200:
          description: Login Successful in application
          schema:
            type: object
            properties:
              token:
                type: string
                format: string
              user:
                type: object
                properties:
                  ID:
                    type: string
                  Name:
                    type: string
                  Email:
                    type: string
                  Address:
                    type: string
                  ImageKey:
                    type: string
                  ImageURL:
                    type: string
                  Phone:
                    type: string
                  Password:
                    type: string
                  FacebookID:
                    type: string
                  Birthday:
                    type: string
                  Gender:
                    type: string
                  CreatedAt:
                    type: string
                  UpdatedAt:
                    type: string
                  DeletedAt:
                    type: string
        500:
          description: Error in application
  /signUp:
    post:
      description: Adiciona novo usuário
      operationId: response
      responses:
        201:
          description: User created
        500:
          description: Error
      tags:
        - user
  /product:
    get:
      tags:
        - product
      description: Buscar todos os produtos
      operationId: response
      responses:
        200:
          description: Lista de produtos
produces:
  - application/json
schemes:
  - https
security:
  - bearer: []
securityDefinitions:
  bearer:
    type: apiKey
swagger: "2.0"
